import type { TransactionType } from "@/types";

interface DefaultCategory {
  name: string;
  type: TransactionType;
  color: string;
  icon: string;
}

export const DEFAULT_INCOME_CATEGORIES: DefaultCategory[] = [
  { name: "Sueldo", type: "income", color: "#ec4899", icon: "Banknote" },
  { name: "Freelance", type: "income", color: "#db2777", icon: "Laptop" },
  { name: "Regalos", type: "income", color: "#be185d", icon: "Gift" },
  { name: "Inversiones", type: "income", color: "#a855f7", icon: "TrendingUp" },
];

export const DEFAULT_EXPENSE_CATEGORIES: DefaultCategory[] = [
  { name: "Comida", type: "expense", color: "#3b82f6", icon: "Utensils" },
  { name: "Transporte", type: "expense", color: "#2563eb", icon: "Car" },
  { name: "Vivienda", type: "expense", color: "#1d4ed8", icon: "Home" },
  { name: "Servicios", type: "expense", color: "#7e22ce", icon: "Zap" },
  { name: "Entretenimiento", type: "expense", color: "#9333ea", icon: "Gamepad2" },
  { name: "Salud", type: "expense", color: "#db2777", icon: "HeartPulse" },
  { name: "Otros", type: "expense", color: "#1f2937", icon: "Package" },
];

export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  ...DEFAULT_INCOME_CATEGORIES,
  ...DEFAULT_EXPENSE_CATEGORIES,
];

export const CATEGORY_COLOR_OPTIONS = [
  "#a855f7",
  "#9333ea",
  "#7e22ce",
  "#ec4899",
  "#db2777",
  "#be185d",
  "#3b82f6",
  "#2563eb",
  "#1d4ed8",
  "#1f2937",
  "#14b8a6",
  "#10b981",
  "#f59e0b",
  "#f97316",
  "#ef4444",
  "#f43f5e",
  "#6366f1",
  "#06b6d4",
  "#8b5cf6",
  "#84cc16",
];

export const CATEGORY_ICON_OPTIONS = [
  "Banknote",
  "PiggyBank",
  "Coins",
  "CreditCard",
  "Receipt",
  "Landmark",
  "Briefcase",
  "Building2",
  "TrendingUp",
  "HandHeart",
  "Handshake",
  "Laptop",
  "Smartphone",
  "Monitor",
  "Wifi",
  "Headphones",
  "Camera",
  "Key",
  "Shield",
  "Bell",
  "CalendarDays",
  "Backpack",
  "GraduationCap",
  "BookOpen",
  "Utensils",
  "Coffee",
  "Pizza",
  "Wine",
  "Beer",
  "IceCreamCone",
  "Popcorn",
  "ChefHat",
  "Apple",
  "Cake",
  "Car",
  "Bus",
  "Plane",
  "TrainFront",
  "TramFront",
  "Bike",
  "Fuel",
  "Anchor",
  "Globe",
  "MapPin",
  "Home",
  "Armchair",
  "Lamp",
  "WashingMachine",
  "Wrench",
  "Hammer",
  "Paintbrush",
  "Zap",
  "Flame",
  "Droplets",
  "Leaf",
  "TreePine",
  "Sun",
  "Umbrella",
  "Snowflake",
  "HeartPulse",
  "Pill",
  "Stethoscope",
  "Dumbbell",
  "Footprints",
  "Gamepad2",
  "Music",
  "Film",
  "Ticket",
  "Trophy",
  "Medal",
  "Rocket",
  "Sparkles",
  "Star",
  "Heart",
  "Dog",
  "Cat",
  "PawPrint",
  "Baby",
  "Shirt",
  "Gift",
  "ShoppingCart",
  "Wallet",
  "Package",
];
